#!/bin/bash
# Language (force it so getopt messages are always in english, as the script)
LANG=en_EN

# Get script name
SCRIPT=$(basename ${0})

# Supported distributions
SUPPORTEDDISTROS="centos7 rockylinux8 amazonlinux2018.03 amazonlinux2 amazonlinux2023"

# Use podman by default as container engine
CENGINE='podman'

# Default registry
REGISTRY='docker.io'

# Allocate tty by default
TTY='-t'

print_info() {
  echo -e "\033[1;36m[INFO] ${1}\033[0m"
}

print_error() {
  echo -e "\033[1;31m[ERROR] ${1}\033[0m"
}

print_ok() {
  echo -e "\033[1;32m[INFO] ${1}\033[0m"
}

print_incorrect_syntax() {
  print_error "Incorrect syntax. Use ${SCRIPT} -h for help"
}

print_error_unsupported_distro() {
  print_error "Unsupported distro. Use ${SCRIPT} -h for help"
}

print_help() {
  echo ""
  echo "Script to perform s3fs-fuse-rpm CI"
  echo ""
  echo "Syntax: "
  echo ""
  echo "${SCRIPT} <ARGUMENTS>"
  echo ""
  echo "Mandatory arguments:"
  echo ""
  echo " --distro=<$(echo ${1}|tr ' ' '|')>"
  echo ""
  echo "Optional arguments:"
  echo ""
  echo "  --name=<CONTAINER_NAME> Define the container name"
  echo "                          If undefined, container name will be"
  echo "                          s3fs-fuse-rpm-<DISTRO>-<TIMESTAMP>"
  echo "  --remove-on-error If present, remove the container on errors"
  echo "  --notty           If present, does not allocate a tty for the container"
  echo "  --docker          Use docker instead of podman"
  echo "  --registry=<REGISTRY> Specify an image registry. If absent, docker.io"
  echo "                       will be used by default"
  echo ""
}

remove_container() {
  ${CENGINE} container rm -f ${1}
}

exit_error() {
  if [ ${1} -ne 0 ]; then
    print_error "An error happened! Check log!"
    if [ ! -z ${REMOVE_ON_ERROR} ]; then
      remove_container ${CONTAINER_NAME}
    fi
    exit 1
  fi
}

container_run() {
  if [ ! -z ${3} ]; then
    local COMMAND_USER="-u ${3}"
  fi
  local COMMAND="${CENGINE} container exec -i ${TTY} ${COMMAND_USER} ${1} ${2}"
  ${COMMAND}
  exit_error ${?}
}

# read the options
ARGS=$(getopt -o h --long help,remove-on-error,notty,distro:,name:,docker:,registry: -n "${SCRIPT}" -- "$@")
if [ $? -ne 0 ];
then
  print_incorrect_syntax
  exit 1
fi
eval set -- "${ARGS}"

# extract options and their arguments into variables
while true ; do
  case "${1}" in
    -h|--help)         print_help "${SUPPORTEDDISTROS}"; exit 1;;
    --remove-on-error) REMOVE_ON_ERROR="TRUE"; shift 1 ;;
    --notty)           TTY=""; shift 1 ;;
    --distro)          DISTRO="${2}"; shift 2;;
    --name)            CONTAINER_NAME="${2}"; shift 2;;
    --docker)          CENGINE='docker'; shift 1;;
    --registry)        REGISTRY="${2}"; shift 2;;
    --)                shift ; break ;;
    *)                 print_incorrect_syntax; exit 1;;
  esac
done

# Check distribution
case "${DISTRO}" in
  centos7)            CONTAINER_IMAGE="${REGISTRY}/centos:centos7" ;;
  rockylinux8)        CONTAINER_IMAGE="${REGISTRY}/rockylinux:8" ;;
  amazonlinux2018.03) CONTAINER_IMAGE="${REGISTRY}/amazonlinux:2018.03" ;;
  amazonlinux2)       CONTAINER_IMAGE="${REGISTRY}/amazonlinux:2" ;;
  amazonlinux2023)    CONTAINER_IMAGE="${REGISTRY}/amazonlinux:2023" ;;
  *)                  print_error_unsupported_distro
                      exit 1;;
esac

# Check name
if [ -z ${CONTAINER_NAME} ]; then
  CONTAINER_NAME="s3fs-fuse-rpm-${DISTRO}-$(date +'%s')"
fi

if [ "${CENGINE}" == "podman" ]; then
  EXTRA_FLAGS="--userns=keep-id"
fi

print_info "Starting container ${CONTAINER_NAME}..."
${CENGINE} container run -i ${TTY} --name "${CONTAINER_NAME}" -v ${PWD}:/tmp/s3fs-fuse-rpm:Z --cap-add SYS_ADMIN --device /dev/fuse -w /tmp/s3fs-fuse-rpm -d ${EXTRA_FLAGS} ${CONTAINER_IMAGE} /bin/bash -c 'while [ 1 -eq 1 ]; do sleep 60; done'
print_info "Cleaning up"
container_run "${CONTAINER_NAME}" "./clean"
if [ "${DISTRO}" == "centos7" ]; then
  print_info "Adjusting CentOS7 repositories to use the vault..."
  mkdir ${PWD}/${CONTAINER_NAME}/
  podman cp ${CONTAINER_NAME}:/etc/yum.repos.d/ ${PWD}/${CONTAINER_NAME}/
  sed -i -e '/^mirrorlist/d;/^#baseurl=/{s,^#,,;s,/mirror,/vault,;}' ${PWD}/${CONTAINER_NAME}/yum.repos.d/CentOS*.repo
  podman cp ${PWD}/${CONTAINER_NAME}/yum.repos.d/ ${CONTAINER_NAME}:/etc/
  rm -rf ${PWD}/${CONTAINER_NAME}/
fi
print_info "Installing required dependencies..."
container_run "${CONTAINER_NAME}" "./install-buildrequires" "root" # Build Dependencies
container_run "${CONTAINER_NAME}" "/usr/bin/yum -q -y install initscripts kernel mailcap openssl grep" "root" # Other dependencies only needed for containers
if [ "${CENGINE}" == "docker" ]; then
  print_info "Configuring user ci..."
  container_run "${CONTAINER_NAME}" "/usr/sbin/groupadd -g $(id -g) ${USER}" "root"
  container_run "${CONTAINER_NAME}" "/usr/sbin/useradd -m -d /home/${USER} -u ${UID} -g $(id -g) ${USER}" "root"
  container_run "${CONTAINER_NAME}" "/bin/chown ci:ci /home/${USER}" "root"
fi
print_info "Installing fuse..."
container_run "${CONTAINER_NAME}" "/usr/bin/yum -q -y install fuse fuse-libs fuse-devel" "root" # fuse
print_info "Building s3fs-fuse package..."
container_run "${CONTAINER_NAME}" "./s3fs-build-rpm" "${USER}"
print_info "Installing s3fs-fuse package..."
container_run "${CONTAINER_NAME}" "/bin/rpm -e fuse-devel" "root"
container_run "${CONTAINER_NAME}" "/bin/rpm -i RPMS/$HOSTTYPE/s3fs-fuse-*.*.$HOSTTYPE.rpm" "root"
print_info "Removing s3fs-fuse package..."
container_run "${CONTAINER_NAME}" "/bin/rpm -e s3fs-fuse" "root"
print_info "Removing container..."
remove_container ${CONTAINER_NAME}
print_ok "Everything OK"
